### ISSUE TITLE
奈良市の小学校区データの作成

### ISSUE THREAD

**Issue by kochizufan** [code4nara/papamama#1]
data/Elementary.geojson

**Comment by YasushiIS** [comment]
国土数値情報データベース（http://nlftp.mlit.go.jp/ksj/index.html）から、小学校区データの奈良県分（A27-10_29_GML）をダウンロードし、/data_org/ 以下に dpf と shp ファイルを登録。
/gulpfile.js で利用するファイル名と市町村コードを奈良市に修正。
gulp updatedata で data/Elementary.geojson を作成し、master にpush。

**Comment by YasushiIS** [comment]
作成完了なのでissue を Closeします。
