### ISSUE TITLE
奈良市の小学校位置データの作成

### ISSUE THREAD

**Issue by kochizufan** [code4nara/papamama#3]
data/Elementary_loc.geojson

**Comment by YasushiIS** [comment]
国土数値情報データベース（http://nlftp.mlit.go.jp/ksj/index.html）から、学校データの奈良県分をダウンロードし、/data_org/ 以下に dbf と shp ファイルを登録。
/gulpfile.js で読み込むファイル名と市町村コードを奈良市に修正しgoejsonファイルを作成。

以上で対応完了。
