### ISSUE TITLE
奈良市の保育園データの作成

### ISSUE THREAD

**Issue by kochizufan** [code4nara/papamama#5]
data/nurseryFacilities.geojson

**Comment by YasushiIS** [comment]
必要なデータを国土数値情報からダウンロードし、data_org 以下に配置。gulp で data/nurseryFacilities.geojson を作成し登録。

**Comment by YasushiIS** [comment]
奈良市提供の保育園データを、data_org/nurseryData.csv　に反映。
CSV１行目の項目を、適当に追加（openSAT：開園時間（土曜）など）
対応有無表示で、○をYに、×をNに置き換えしてコミット。
gulp を使い、data/nurseryFacilities.geojson の内容を更新しコミット。

以上でデータ作成は完了。
課題はデータ更新方法の共有。
