### ISSUE TITLE
区情報なしで動くようにする？

### ISSUE THREAD

**Issue by kochizufan** [code4nara/papamama#7]
data/wards.geojson
は奈良にないので削除対応必要？
鼓坂 済美 都祁などの地域の概念を当てはめる？

**Comment by YasushiIS** [comment]
自動作成の対象から data/wards.geojson を外すように /gulpfile.js を修正。
data/wards.geojson  をサイズ０にして暫定対応。

**Comment by YasushiIS** [comment]
動作にないので現状維持で進める
